version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 8888:80
      - 8443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./data/:/www/data/:ro
      - ./cert/:/etc/nginx/ssl/:ro
